"""
report.py
---------
PURPOSE : Build a formatted plain-text report that users can download.
          Combines the summary and all risks into one readable file.

USED BY : app.py (when user clicks the Download button)
DEPENDS ON : datetime (built-in Python, no install needed)

HOW IT WORKS:
  1. Take the summary and risk list as inputs
  2. Format them into a nicely structured text document
  3. Return the full text as a string
  4. Streamlit's download_button will let user save it as .txt
"""

from datetime import datetime   # built-in Python library


def generate_report(doc_type, summary, risks, clause_ranking=None, filename="contract"):
    """
    Build a full plain-text analysis report.

    PARAMETERS:
        doc_type (str)  : type of document (e.g. "Rental Agreement")
        summary  (str)  : plain English summary from Claude
        risks    (list) : parsed risk list from risk_formatter.py
        filename (str)  : original uploaded file name

    RETURNS:
        str : complete report as a single string
              (Streamlit will offer this as a .txt download)

    PERSON 6 — HOW TO TEST:
        Create a fake summary string and a fake risks list.
        Call this function and print the result.
        Check that all sections appear correctly.
    """

    # Get current date and time for the report header
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = []   # we build the report line by line, then join at the end

    #  HEADER 
    lines.append("=" * 60)
    lines.append("   LEGAL DOCUMENT ANALYSIS REPORT")
    lines.append("   Generated by: Legal Plain Talk")
    lines.append(f"   Date     : {now}")
    lines.append(f"   File     : {filename}")
    lines.append(f"   Doc Type : {doc_type}")
    lines.append("=" * 60)
    lines.append("")

    # ── CLAUSE IMPORTANCE RANKING ────────────────────────
    if clause_ranking:
        lines.append("TOP 5 CLAUSES TO READ FIRST")
        lines.append("-" * 40)
        lines.append("(Read these before anything else — ranked by importance)")
        lines.append("")
        for item in clause_ranking:
            lines.append(f"  #{item['rank']}  {item['title']}")
            lines.append(f"      Find it  : \"{item['location']}\"")
            lines.append(f"      Why read : {item['why_important']}")
            lines.append("")
        lines.append("")

    # ── PLAIN ENGLISH SUMMARY ───────────────────────────
    lines.append("PLAIN ENGLISH SUMMARY")
    lines.append("-" * 40)
    lines.append(summary)
    lines.append("")

    # ── RISK COUNTS ─────────────────────────────────────
    lines.append("RISK SURFACE MAP — OVERVIEW")
    lines.append("-" * 40)

    high_risks   = [r for r in risks if r["risk_level"].upper() == "HIGH"]
    medium_risks = [r for r in risks if r["risk_level"].upper() == "MEDIUM"]
    low_risks    = [r for r in risks if r["risk_level"].upper() == "LOW"]

    lines.append(f"  HIGH   risk clauses : {len(high_risks)}")
    lines.append(f"  MEDIUM risk clauses : {len(medium_risks)}")
    lines.append(f"  LOW    risk clauses : {len(low_risks)}")
    lines.append("")

    # ── DETAILED RISK LIST ───────────────────────────────
    lines.append("DETAILED RISK BREAKDOWN")
    lines.append("-" * 40)

    if not risks:
        lines.append("No significant risks were detected in this document.")
    else:
        for i, risk in enumerate(risks, start=1):
            lines.append(f"Issue #{i}  [{risk['risk_level']}]")
            lines.append(f"  Clause      : {risk['clause']}")
            lines.append(f"  Meaning     : {risk['plain_english']}")
            lines.append(f"  Why Bad     : {risk['why_risky']}")
            lines.append("")

    # ── FOOTER / DISCLAIMER ─────────────────────────────
    lines.append("=" * 60)
    lines.append("IMPORTANT DISCLAIMER")
    lines.append("This report is generated by an AI system.")
    lines.append("It is NOT legal advice.")
    lines.append("Always consult a qualified lawyer before signing")
    lines.append("any legal document.")
    lines.append("=" * 60)

    # Join all lines into one big string
    return "\n".join(lines)
